GENERALA = {'name': "generala", 'score': 50}
POKER = {'name': "poker", 'score': 45}
FULL = {'name': "full", 'score': 30}
ESCALERA = {'name': "escalera", 'score': 20}
GENERALASERVIDA = {'name': 'generalaServida'}
FULL_SERVIDO = {'name': 'fullServido', 'score': 35}
ESCALERA_SERVIDO = {'name': 'escaleraServida', 'score': 25}
UNO = {'name': 'UNO', 'score': 0}
DOS = {'name': 'DOS', 'score': 0}
TRES = {'name': 'TRES', 'score': 0}
CUATRO = {'name': 'CUATRO', 'score': 0}
CINCO = {'name': 'CINCO', 'score': 0}
SEIS = {'name': 'SEIS', 'score': 0}
