GENERALA = {'name': "generala", 'score': 50}
POKER = {'name': "poker", 'score': 45}
FULL = {'name': "full", 'score': 30}
ESCALERA = {'name': "escalera", 'score': 20}
GENERALASERVIDA = {'name': 'generalaServida'}
FULL_SERVIDO = {'name': 'fullServido', 'score': 35}
ESCALERA_SERVIDO = {'name': 'escaleraServida', 'score': 25}
UNO = 1
DOS = 2
TRES = 3
CUATRO = 4
CINCO = 5
SEIS = 6
